### ISSUE TITLE
Generate Packages bring "File not found exception"

### ISSUE THREAD

**Issue by GuidoLeibbrand** [caioproiete/DevExpress-NuGet#10]
Hi CaioProiete,

first thank you for this Project :+1: 

I use the current Devexpress Version 15.1.3. When i start to generate the packages via PS ".\nuget-pack.ps1" i get the follow error:

File not found: 'lib\DevExpress.Charts.Designer.v15.1.xml'.
C:_Data\Work\head\DevExpress-NuGet\src\nuget-pack.ps1 : Error generating nupkg for 'Unofficial.DevExpress.Charts.Desig
ner.nuspec'
Bei Zeile:1 Zeichen:17
- .\nuget-pack.ps1 <<<<
  - CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
  - FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,nuget-pack.ps1

First i removed this xml file deklaration from the nuspec-File and start again. But then the Script break at one of the next files. I stoppt this after 10 remove and retrys.

My question: Can you publish you nuspec-File generator tool. So i can start it local on my maschine and create nuspec-File with a working with my current devexpress installation (check file exists), right?

Also i can add the language feature. In my case i only need the german language

Thank you.

Guido

**Comment by CaioProiete** [comment]
Hi @GuidoLeibbrand, thanks for the feedback.

It's on my "to do" list to rewrite the "nuspec-file generator tool" and make it a command-line utility that can dynamically generate the nuspec files based on the files available in the folder you point it to. I just didn't get around that yet...

In the meantime, the easiest way to get around this is to install all the items in the DevExpress installer (and you can uninstall right after generating the nuspec files). See [this comment](https://github.com/CaioProiete/DevExpress-NuGet/issues/7#issuecomment-97961656) on issue #7 for more details.

Thanks,
Caio Proiete
