### ISSUE TITLE
DevExpress v15.2.X

### ISSUE THREAD

**Issue by StefanDoubleU** [caioproiete/DevExpress-NuGet#12]
Hello,

can you please provide nuspec definitions for version 15.2.X. Latest version is 15.2.3

With best regards,
Stefan

**Comment by Birgos** [comment]
**+1**
Maybe now you would agree to publish your "quick and dirty c# code", so others could submit pull requests in case of new DevExpress versions? **;-)**

**Comment by caioproiete** [comment]
There you go guys:

**NuGet Packages for the DevExpress .NET Components v15.2.3**
https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v15.2.3

---

@Birgos Yeah, that is definitely something I've got to do, isn't it?
Let me try get some time in the next few weeks and make this happen. Hopefully I can get something before the January release.
