### ISSUE TITLE
generate the packages with correct dependencies

### ISSUE THREAD

**Issue by smoothdeveloper** [caioproiete/DevExpress-NuGet#15]
I made a similar script which generates nuget nuspec and packages with correct dependencies:

https://gist.github.com/smoothdeveloper/994522269a0a04c275c9

In this repository it is mentioned:

> The nuspec files are currently being generated by a quick-and-dirty C# app that I wrote, which is not ready to be shared with the world :)

I think the fsharp script in my gist could replace that C# app which is not published, so I just wanted to share it for other users that might want to use it in case this repository doesn't get updated with future release or if they want to use it with older releases.

**Comment by fpellet** [comment]
I continued smoothdeveloper's works : https://github.com/fpellet/convertToNuGet

I added a script to facilitate run and added external nuget support (EntityFramework)
