### ISSUE TITLE
Generate v17.1.6 Release

### ISSUE THREAD

**Issue by ericmschmidt** [caioproiete/DevExpress-NuGet#19]
Could you generate the files needed to create v17.1.6 NuGet packages? Any update to publishing the source code to generate the .nuspec files?

**Comment by ericmschmidt** [comment]
Actually, 17.1.7 would be even better. Thanks in advance.

**Comment by caioproiete** [comment]
@ericmschmidt Both [v17.1.6](https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v17.1.6) and [v17.1.7](https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v17.1.7) are now available.

* **v17.1.7** - https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v17.1.7
* **v17.1.6** - https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v17.1.6

**Comment by ericmschmidt** [comment]
Thank you. This project has been extremely helpful with our applications.
