### ISSUE TITLE
17.2.5 Package Definitions

### ISSUE THREAD

**Issue by ericmschmidt** [caioproiete/DevExpress-NuGet#21]
Could you please generate and publish the scripts for v17.2.5?

**Comment by caioproiete** [comment]
@ericmschmidt NuGet specs for the latest releases from DevExpress published:

* **v17.2.5** - https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v17.2.5
* **v17.2.4** - https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v17.2.4
* **v17.2.3** - https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v17.2.3
* **v17.1.9** - https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v17.1.9
* **v17.1.8** - https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v17.1.8
