### ISSUE TITLE
Generate 18.1.5

### ISSUE THREAD

**Issue by ericmschmidt** [caioproiete/DevExpress-NuGet#22]
Could you generate the scripts for 18.1.4?

**Comment by ericmschmidt** [comment]
Actually 18.1.5 would be great since that just came out

**Comment by caioproiete** [comment]
@ericmschmidt Will try to get this done over the weekend

**Comment by caioproiete** [comment]
Done. https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v18.1.5
