### ISSUE TITLE
Generate 18.1.6 nuspec

### ISSUE THREAD

**Issue by ericmschmidt** [caioproiete/DevExpress-NuGet#23]
Hello,

DevExpress just released v18.1.6, which has a few critical updates to issues we found in 18.1.5. Could you please generate the v18.1.6 nuspec files?

**Comment by ericmschmidt** [comment]
Any idea when you'll be able to get to this?

**Comment by caioproiete** [comment]
@ericmschmidt Best case scenario tomorrow night (Sep 18th), worst case scenario Sunday night (22nd).

**Comment by ericmschmidt** [comment]
@caioproiete Thanks for the update.

**Comment by caioproiete** [comment]
https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v18.1.6

**Comment by ericmschmidt** [comment]
Thanks.
