### ISSUE TITLE
Update script to use proper .NET Framework Version

### ISSUE THREAD

**Issue by ericmschmidt** [caioproiete/DevExpress-NuGet#25]
With the release of v18.2, DevExpress upgraded all packages to use .NET Framework 4.5.2. While I believe I can go in and update the .nuspec for 18.2.7 I wondered if you could update your generating script to define the proper .NET Framework version.

**Comment by caioproiete** [comment]
Thanks for the heads-up @ericmschmidt. I'll update this repo with DevExpress v19.1.5 soon, and will update the .NET Framework version for the versions you pointed out in the process.

**Comment by caioproiete** [comment]
Script updated to target .NET Framework 4.5.2 moving forward.

For the sake of consistency, I've released updated NuGet specs from `v18.2.3` to `v19.1.4`:

- [v19.1.4-net452](https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v19.1.4-net452)
- [v19.1.3-net452](https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v19.1.3-net452)
- [v18.2.9-net452](https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v18.2.9-net452)
- [v18.2.8-net452](https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v18.2.8-net452)
- [v18.2.7-net452](https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v18.2.7-net452)
- [v18.2.6-net452](https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v18.2.6-net452)
- [v18.2.5-net452](https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v18.2.5-net452)
- [v18.2.4-net452](https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v18.2.4-net452)
- [v18.2.3-net452](https://github.com/caioproiete/DevExpress-NuGet/releases/tag/v18.2.3-net452)
