### ISSUE TITLE
DevExpress 14.2.3

### ISSUE THREAD

**Issue by mterwoord** [CaioProiete/DevExpress-NuGet#3]
Devexpress 14.2 was released. Any chance you could provide the nuspec files for that as well?
(or maybe just put up the tool you use somewhere..)

**Comment by CaioProiete** [comment]
Hi @mterwoord, I've added the nuspec files for DevExpress [v14.2.3](https://github.com/CaioProiete/DevExpress-NuGet/releases/tag/v14.2.3) and [v14.2.4](https://github.com/CaioProiete/DevExpress-NuGet/releases/tag/v14.2.4).

Let me know if you run into any issues.

**Comment by mterwoord** [comment]
Cool. I didn't even remember this project, until you fixed this issue. At work, I already generated them myself.. Sorry for the hassle..
