### ISSUE TITLE
Write Powershell script to generate the NuGet packages from the .nuspec files

### ISSUE THREAD

**Issue by CaioProiete** [CaioProiete/DevExpress-NuGet#5]
The script nuget-pack.cmd should be converted to a simpler Powershell script that enumerates the nuspec files and calls the nuget.exe utility, instead of having all the calls hard-coded in a batch file

**Comment by ir2000** [comment]
Could you update the readme to reflect this change?

**Comment by caioproiete** [comment]
Hi @ir2000, it has been on the readme since I've introduced it:

https://github.com/caioproiete/DevExpress-NuGet#how-to-generate-the-nuget-packages

![image](https://cloud.githubusercontent.com/assets/177608/20149155/e453d4be-a664-11e6-94ad-6d0c4c4698d3.png)

What is missing?

**Comment by caioproiete** [comment]
@ir2000 Done. Thanks for the heads-up!
