### ISSUE TITLE
About references in *.config

### ISSUE THREAD

**Issue by exalted** [caioproiete/DevExpress-NuGet#9]
How these packages add various references in `*.config` files to load assemblies and whatnot please?

**Comment by CaioProiete** [comment]
Hi @exalted, are you talking about assembly binding redirects?

If that is the case, then it's not these packages (directly) adding these... NuGet (or Visual Studio) is doing that.

This typically happens if a project is referencing an old version of a library - without using NuGet - so it can redirect to the new ones being added via NuGet.

If you remove all the old references from all projects, and only use the NuGet packages to install the DevExpress components, you should not get any binding redirects in your App.config files.

**Comment by exalted** [comment]
I am referring to stuff like

```xml
    <sectionGroup name="devExpress">
      <section name="themes" type="DevExpress.Web.ASPxClasses.ThemesConfigurationSection, DevExpress.Web.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" requirePermission="false" />
      <section name="compression" type="DevExpress.Web.ASPxClasses.CompressionConfigurationSection, DevExpress.Web.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" requirePermission="false" />
      <section name="settings" type="DevExpress.Web.ASPxClasses.SettingsConfigurationSection, DevExpress.Web.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" requirePermission="false" />
      <section name="errors" type="DevExpress.Web.ASPxClasses.ErrorsConfigurationSection, DevExpress.Web.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" requirePermission="false" />
    </sectionGroup>
```

or

```xml
      <assemblies>
        <add assembly="DevExpress.Data.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
        <add assembly="DevExpress.Web.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
        <add assembly="DevExpress.Web.ASPxHtmlEditor.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
        <add assembly="DevExpress.Web.ASPxSpellChecker.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
        <add assembly="DevExpress.Web.ASPxTreeList.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
        <add assembly="DevExpress.Web.ASPxThemes.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
        <add assembly="DevExpress.Web.ASPxPivotGrid.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
        <add assembly="DevExpress.Utils.v13.1, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
        <add assembly="DevExpress.Office.v13.1.Core, Version=13.1.11.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a" />
```

**Comment by CaioProiete** [comment]
Hi @exalted,

The packages are not (explicitly) adding anything to your config files... I suspect either Visual Studio is doing that as references get added to your project, or it is being done by the DevExpress extensions you have running in Visual Studio.

I suggest you ask this in the [DevExpress forum](https://community.devexpress.com/forums/)...

Thanks,
Caio Proiete

**Comment by exalted** [comment]
@CaioProiete I am curious though, how does it work for you. Do you have `namespace` references added in your `Web.config` or do you add whatever is necessary manually, after Nuget install?

**Comment by CaioProiete** [comment]
@exalted: Sure. Are you installing these packages in any specific order?

**Comment by exalted** [comment]
So weird. I always though Devexpress' tooling would add those references automagically, I didn't know that via NuGet you would still get all those `namespace` imports for an MVC project.

**Comment by caioproiete** [comment]
@exalted: Will close this one. Please feel free to comment/re-open if you find any issue related to that.
